"""add cascade delete to scan and finding foreign keys

Revision ID: 2266913b8cce
Revises: e2862a3e6272
Create Date: 2026-07-11 10:33:24.429379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2266913b8cce'
down_revision = 'e2862a3e6272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('findings_scan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'scans', ['scan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('scans_website_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'websites', ['website_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scans_website_id_fkey'), 'websites', ['website_id'], ['id'])

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('findings_scan_id_fkey'), 'scans', ['scan_id'], ['id'])

    # ### end Alembic commands ###
