"""add share token fields to scans

Revision ID: 38719f3f9ac3
Revises: ee70e0da2744
Create Date: 2026-07-21 10:53:53.064726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38719f3f9ac3'
down_revision = 'ee70e0da2744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('share_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scans_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_share_token'))
        batch_op.drop_column('share_token_expires_at')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
