"""add scheduling fields to websites

Revision ID: c145f0e58ab8
Revises: 2266913b8cce
Create Date: 2026-07-15 09:27:44.890550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c145f0e58ab8'
down_revision = '2266913b8cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_run_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_websites_next_run_at'), ['next_run_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_next_run_at'))
        batch_op.drop_column('next_run_at')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
