"""add notify_on_critical_findings to users

Revision ID: ee70e0da2744
Revises: c145f0e58ab8
Create Date: 2026-07-19 11:40:13.809083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee70e0da2744'
down_revision = 'c145f0e58ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_on_critical_findings', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_on_critical_findings')

    # ### end Alembic commands ###
